spring.application.name=Process Order

camunda.client.mode=self-managed
camunda.client.grpc-address=http://127.0.0.1:26500
camunda.client.rest-address=http://127.0.0.1:8088
camunda.client.auth.username=demo
camunda.client.auth.password=demo
camunda.client.request-timeout=PT30S

server.port=8081


logging.level.io.camunda.client.impl.CamundaCallCredentials=ERROR

